{
 "title": "Pizza Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service-dev\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "revenue{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(request_total{method=\"GET\"}[1m])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "rate(request_total{method=\"all\"}[1m])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "rate(request_total{method=\"PUT\"}[1m])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "rate(request_total{method=\"POST\"}[1m])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "rate(request_total{method=\"DELETE\"}[1m])",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Pizzas sold",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(pizzas_sold{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Pizzas Sold"
    },
    {
     "expr": "rate(creation_failures{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Purchase Failures"
    }
   ]
  },
  {
   "title": "Authentication Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(auth_success_count{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Successful"
    },
    {
     "expr": "rate(auth_failure_count{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "latency{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "active_users_count{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "Usage Data",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "CPU  Usage"
    },
    {
     "expr": "memory_usage{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Grafana Metrics Assignment",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(demo_instant[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests - Grafana Assignment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(request_total{method=\"GET\"}[1m])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "rate(request_total{method=\"POST\"}[1m])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "rate(request_total{method=\"DELETE\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}